### ISSUE TITLE
Set develop as default branch?

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-simox-models#1]
In this repo, as in many others, master/develop gitflow is followed. This is good!
Coud we change (via settings) the default branch to be `develop`, as in other repos?

**Comment by AlvaroMartinezR** [comment]
Yes, makes sense and it should be this way, I will do it. Only one problem that @RaulFdzbis was explaining me is that in this context `master` should be used instead of `develop`, for example for dynamic information.

**Comment by jgvictores** [comment]
> Only one problem that @RaulFdzbis was explaining me is that in this context `master` should be used instead of `develop`, for example for dynamic information.

From https://github.com/roboticslab-uc3m/best-practices/issues/6 (and thus at https://github.com/roboticslab-uc3m/best-practices/) we decided to distinguish pure-documentation repos with only `master`, and general repositories (not pure-documentation) with gitflow (`master/develop`). On a general repository (not pure-documentation), basically anything should default to `develop`. While these files are documentation, since they are on a general repository (not pure-documentation), they should go on `develop` first. Thanks!
